apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tasteless-mammal-python 
  janus-idp.io/tekton: tasteless-mammal-python
  backstage.io/kubernetes-id: tasteless-mammal-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: tasteless-mammal-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  